
export const PUSH_NAVIGATION = 'PUSH_NAVIGATION';
export const POP_NAVIGATION = 'POP_NAVIGATION';
export const REPLACE_NAVIGATION = 'REPLACE_NAVIGATION';

export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';

export const MARK_QUESTIONS_COMPLETED = 'MARK_QUESTIONS_COMPLETED';
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const CLEAR_QUESTIONS = 'CLEAR_QUESTIONS';
