
export const SELECT_POKEMON = 'SELECT_POKEMON';
export const DESELECT_POKEMON = 'DESELECT_POKEMON';

export const PUSH_NAVIGATION = 'PUSH_NAVIGATION';
export const POP_NAVIGATION = 'POP_NAVIGATION';
export const REPLACE_NAVIGATION = 'REPLACE_NAVIGATION';

export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';
